name: calendar_app
description: "A new Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # logging
  logging:

  # http
  dio:

  # desktop management
  window_manager:

  # storage
  flutter_secure_storage:

  # state management
  flutter_riverpod:
  riverpod_annotation:

  # freezed
  freezed_annotation:

  # datetime format
  intl:
  # local dataSource
  sqflite:
  path:
  # env
  flutter_dotenv:

  # router
  go_router:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  riverpod_generator:
  freezed:
  json_serializable:
  source_gen:

flutter:
  uses-material-design: true
  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700